### ISSUE TITLE
Trying to download dataset, it says "Dataset is malformed"

### ISSUE THREAD

**Issue by anthony0727** [AI4Science-WestlakeU/cindm#2]
I'm trying to download the dataset in the README,

but when I click the link I get "Dataset is malformed"

Thanks!

**Comment by Zhangtao167** [comment]
I'm sorry. We just double-checked the link, and it's fine. Maybe you can try logging out of your Google account and clicking the link. If that fails, can you provide more details so that I can help you download the dataset?

**Comment by anthony0727** [comment]
Oh now I can download it! probably it was temporary problem on my side.

Thanks!!
